apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector: # Seleciona, link entre o flask.yaml e flask-service, vai expor o container...
    app: flask-app
  ports:
    - protocol: 'TCP'
      port: 5000
      targetPort: 5000
  type: LoadBalancer
  
