apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec: # Definição geral do deployment
  replicas: 4
  selector: 
    matchLabels:
      app: flask-app
  template: # Como esse aplicativo/template vai rodar
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask
          image: luizhs3/flask-kube-projeto:2