version: '3.3'

services:
  db:
    build: ./mysql/
    restart: always
    env_file:
      - ./config/db.env
    ports:
      - "3306:3306"
    networks:
      - dockercompose
  
  flask:
    depends_on:
      - db
    build: ./flask/
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - "C:\\Users\\Luiz\\Desktop\\Docker\\docker\\compose\\bind_mount\\flask:/app"
    networks:
      - dockercompose

networks:
  dockercompose:
    driver: bridge